baseURL = 'https://zh1995.github.io/'
languageCode = 'cn'
title = 'Final World'
theme = 'smol'
copyright = "ZH1995"
# Parameters
[params]
    subtitle = "This is my farmland!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

    [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3

# Footer
    [[menu.footer]]
        name = "Github"
        url = "https://github.com/ZH1995"
        weight = 1 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/RWZSJFM"
        weight = 2 

    [[menu.footer]]
        name = "Bilibili"
        url = "https://space.bilibili.com/8382675"
        weight = 3 