baseURL = 'https://zh1995.github.io/'
languageCode = 'cn'
title = '桃花源'
theme = 'smol'
copyright = "ZH1995"
# Parameters
[params]
    subtitle = "我的庄稼地!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 1 
        title = "文章"

    [[menu.main]]
        identifier = "categories"
        name = "分类"
        url = "/categories/"
        weight = 2 

    [[menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 3

# Footer
    [[menu.footer]]
        name = "Github"
        url = "https://github.com/ZH1995"
        weight = 1 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/RWZSJFM"
        weight = 2 

    [[menu.footer]]
        name = "Bilibili"
        url = "https://space.bilibili.com/8382675"
        weight = 3 